[package]
name = "mtos-runtime"
version = "0.1.0"
edition = "2021"
authors = ["MTOS Project"]
description = "Runtime library for MTOS userspace applications"
license = "MIT"

[dependencies]
heapless = "0.7"
